version: "3.1"

services:

  db:
    container_name: servidor_mysql
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: bookmedik
      MYSQL_USER: bookmedik
      MYSQL_PASSWORD: bookmedik
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/mariajesus/Docker/Volumes:/var/lib/mysql
  bookmedik:
    container_name: bookmedik
    image: mariajesusbp/bookmedik:v1_2
    restart: always
    ports:
      - 8080:80
    volumes:
      - /home/mariajesus/Docker/Volumes:/var/log/apache2
